services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:5173"
    environment:
      VITE_USE_POLLING: "true"
      VITE_POLLING_INTERVAL: "5000"
    volumes:
      - .:/app
      - /app/node_modules
