export const WORLD_COUNTRIES_MAP_BACKGROUND = '#202326'
export const WORLD_COUNTRIES_MAP_COUNTRY_FILL = '#5A5E66'
export const WORLD_COUNTRIES_MAP_COUNTRY_STROKE = '#2A2D33'
export const WORLD_COUNTRIES_MAP_COUNTRY_STROKE_WIDTH = '1.05px'
export const WORLD_COUNTRIES_MAP_LABEL_FILL = '#DDE0E5'
export const WORLD_COUNTRIES_MAP_LABEL_OPACITY = 0.8
export const WORLD_COUNTRIES_MAP_SELECTION_STROKE = '#73CDD4'
